<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageConstatntSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $language_constant_record = [
            [
                'id' => 1,
                'constant_name' => 'GET',
                'value' => 'Get',
                'pt_value' => 'Pegar',
                'vi_value' => 'Lấy',
                'he_value' => 'לקבל',
                'de_value' => 'Bekommen',
                'es_value' => 'Conseguir',
                'fr_value' => 'Obtenir',
                'ko_value' => '얻다',
                'ja_value' => '取得する',
                'zh_value' => '得到',
                'fil_value' => 'Kunin',
                'ar_value' => 'يحصل',
            ],
            [
                'id' => 2,
                'constant_name' => 'OFF_ON_ALL_ORDERS',
                'value' => 'off on all orders',
                'pt_value' => 'desligado em todos os pedidos',
                'vi_value' => 'tắt trên tất cả các đơn đặt hàng',
                'he_value' => 'הנחה על כל ההזמנות',
                'de_value' => 'aus auf alle Bestellungen',
                'es_value' => 'apagado en todos los pedidos',
                'fr_value' => 'de réduction sur toutes les commandes',
                'ko_value' => '모든 주문에서 해제',
                'ja_value' => 'すべての注文でオフ',
                'zh_value' => '所有订单关闭',
                'fil_value' => 'off sa lahat ng orders',
                'ar_value' => 'قبالة على جميع الطلبات',
            ],
            [
                'id' => 3,
                'constant_name' => 'OFF_ON_ORDERS_ABOVE',
                'value' => 'off on orders above',
                'pt_value' => 'off em pedidos acima',
                'vi_value' => 'tắt theo đơn hàng trên',
                'he_value' => 'הנחה על הזמנות לעיל',
                'de_value' => 'Rabatt auf Bestellungen oben',
                'es_value' => 'descuento en pedidos anteriores',
                'fr_value' => 'de réduction sur les commandes ci-dessus',
                'ko_value' => '위의 주문에서 해제',
                'ja_value' => '上記の注文でオフ',
                'zh_value' => '以上订单关闭',
                'fil_value' => 'off sa mga order sa itaas',
                'ar_value' => 'على الطلبات أعلاه',
            ],
            [
                'id' => 4,
                'constant_name' => 'RIDE_SERVICE',
                'value' => 'Ride Service',
                'pt_value' => 'Serviço de passeio',
                'vi_value' => 'Dịch vụ đi xe',
                'he_value' => 'שירות הסעות',
                'de_value' => 'Fahrdienst',
                'es_value' => 'Servicio de paseo',
                'fr_value' => 'Service de transport',
                'ko_value' => '승차 서비스',
                'ja_value' => 'ライドサービス',
                'zh_value' => '乘车服务',
                'fil_value' => 'Serbisyo sa Pagsakay',
                'ar_value' => 'خدمة الركوب',
            ],
            [
                'id' => 5,
                'constant_name' => 'COURIER_DELIVERY',
                'value' => 'Courier Delivery',
                'pt_value' => 'Entrega de correio',
                'vi_value' => 'Giao hàng chuyển phát nhanh',
                'he_value' => 'משלוח שליחים',
                'de_value' => 'Kurierlieferung',
                'es_value' => 'Entrega de mensajería',
                'fr_value' => 'La livraison de courrier',
                'ko_value' => '택배 배송',
                'ja_value' => '宅配便',
                'zh_value' => '快递送货',
                'fil_value' => 'Paghahatid ng Courier',
                'ar_value' => 'تسليم البريد السريع',
            ],
            [
                'id' => 6,
                'constant_name' => 'STORE_DELIVERY',
                'value' => 'Store Delivery',
                'pt_value' => 'Entrega na loja',
                'vi_value' => 'Cửa hàng giao hàng',
                'he_value' => 'משלוח לחנות',
                'de_value' => 'Lieferung im Laden',
                'es_value' => 'Entrega en tienda',
                'fr_value' => 'Livraison en magasin',
                'ko_value' => '매장 배송',
                'ja_value' => '店舗配送',
                'zh_value' => '门店配送',
                'fil_value' => 'Paghahatid sa Tindahan',
                'ar_value' => 'التسليم في المتجر',
            ],
            [
                'id' => 7,
                'constant_name' => 'RENTAL_SERVICE',
                'value' => 'Rental Service',
                'pt_value' => 'Serviço de aluguel',
                'vi_value' => 'Dịch vụ cho thuê',
                'he_value' => 'שירות השכרה',
                'de_value' => 'Verleih',
                'es_value' => 'Servicio de renta',
                'fr_value' => 'Service de location',
                'ko_value' => '렌탈 서비스',
                'ja_value' => 'レンタルサービス',
                'zh_value' => '租赁服务',
                'fil_value' => 'Serbisyo sa Pagpapaupa',
                'ar_value' => 'خدمة تأجير',
            ],
            [
                'id' => 8,
                'constant_name' => 'SUN',
                'value' => 'Sun',
                'pt_value' => 'Sol',
                'vi_value' => 'Mặt trời',
                'he_value' => 'שמש',
                'de_value' => 'Sonne',
                'es_value' => 'Sol',
                'fr_value' => 'Soleil',
                'ko_value' => '해',
                'ja_value' => '太陽',
                'zh_value' => '太阳',
                'fil_value' => 'Araw',
                'ar_value' => 'شمس',
            ],
            [
                'id' => 9,
                'constant_name' => 'MON',
                'value' => 'Mon',
                'pt_value' => 'seg',
                'vi_value' => 'Thứ hai',
                'he_value' => 'יום שני',
                'de_value' => 'Mo',
                'es_value' => 'Lun',
                'fr_value' => 'Lun',
                'ko_value' => '월',
                'ja_value' => '月',
                'zh_value' => '星期一',
                'fil_value' => 'Mon',
                'ar_value' => 'الإثنين',
            ],
            [
                'id' => 10,
                'constant_name' => 'TUE',
                'value' => 'Tue',
                'pt_value' => 'ter',
                'vi_value' => 'thứ ba',
                'he_value' => 'ג\'',
                'de_value' => 'Di',
                'es_value' => 'Mar',
                'fr_value' => 'Mar',
                'ko_value' => '화',
                'ja_value' => '火',
                'zh_value' => '星期二',
                'fil_value' => 'Tue',
                'ar_value' => 'الثلاثاء',
            ],
            [
                'id' => 11,
                'constant_name' => 'WED',
                'value' => 'Wed',
                'pt_value' => 'qua',
                'vi_value' => 'Thứ Tư',
                'he_value' => 'היינו עושים',
                'de_value' => 'Heiraten',
                'es_value' => 'Casarse',
                'fr_value' => 'Épouser',
                'ko_value' => '수',
                'ja_value' => '結婚した',
                'zh_value' => '星期三',
                'fil_value' => 'ikasal',
                'ar_value' => 'تزوج',
            ],
            [
                'id' => 12,
                'constant_name' => 'THU',
                'value' => 'Thu',
                'pt_value' => 'qui',
                'vi_value' => 'Thứ năm',
                'he_value' => 'יום ה\'',
                'de_value' => 'Do',
                'es_value' => 'Jue',
                'fr_value' => 'Jeu',
                'ko_value' => '목',
                'ja_value' => '木',
                'zh_value' => '星期四',
                'fil_value' => 'Huwebes',
                'ar_value' => 'خميس',
            ],
            [
                'id' => 13,
                'constant_name' => 'FRI',
                'value' => 'Fri',
                'pt_value' => 'sex',
                'vi_value' => 'Thứ Sáu',
                'he_value' => 'שישי',
                'de_value' => 'Fr',
                'es_value' => 'Vie',
                'fr_value' => 'Ven',
                'ko_value' => '금',
                'ja_value' => '金',
                'zh_value' => '星期五',
                'fil_value' => 'Biyernes',
                'ar_value' => 'الجمعة',
            ],
            [
                'id' => 14,
                'constant_name' => 'SAT',
                'value' => 'Sat',
                'pt_value' => 'Sentada',
                'vi_value' => 'Đã ngồi',
                'he_value' => 'ישב',
                'de_value' => 'Sa',
                'es_value' => 'Sentó',
                'fr_value' => 'Sam',
                'ko_value' => '수능',
                'ja_value' => '土',
                'zh_value' => '星期六',
                'fil_value' => 'Sab',
                'ar_value' => 'قعد',
            ],
            [
                'id' => 15,
                'constant_name' => 'FEATURED',
                'value' => 'Feature',
                'pt_value' => 'Recurso',
                'vi_value' => 'Tính năng',
                'he_value' => 'תכונה',
                'de_value' => 'Besonderheit',
                'es_value' => 'Rasgo',
                'fr_value' => 'Caractéristique',
                'ko_value' => '특징',
                'ja_value' => '特徴',
                'zh_value' => '特征',
                'fil_value' => 'Tampok',
                'ar_value' => 'ميزة',
            ],
            [
                'id' => 16,
                'constant_name' => 'IN_SPOT_LIGHT',
                'value' => 'In Spot Light !',
                'pt_value' => 'Em Spot Light!',
                'vi_value' => 'Trong ánh sáng tại chỗ!',
                'he_value' => 'באור נקודתי!',
                'de_value' => 'Im Rampenlicht!',
                'es_value' => '¡En Spot Light!',
                'fr_value' => 'En Spotlight !',
                'ko_value' => '스포트 라이트에서!',
                'ja_value' => 'スポットライトで！',
                'zh_value' => '在聚光灯下！',
                'fil_value' => 'Sa Spot Light!',
                'ar_value' => 'في بقعة ضوء!',
            ],
            [
                'id' => 17,
                'constant_name' => 'FAVORITE',
                'value' => 'Favorite',
                'pt_value' => 'Favorita',
                'vi_value' => 'Yêu thích',
                'he_value' => 'אהוב',
                'de_value' => 'Lieblings',
                'es_value' => 'Favorito',
                'fr_value' => 'Préférée',
                'ko_value' => '가장 좋아하는',
                'ja_value' => 'お気に入り',
                'zh_value' => '最喜欢的',
                'fil_value' => 'Paborito',
                'ar_value' => 'مفضل',
            ],
            [
                'id' => 18,
                'constant_name' => 'RECOMMENDED',
                'value' => 'Recommended',
                'pt_value' => 'Recomendada',
                'vi_value' => 'Khuyến khích',
                'he_value' => 'מוּמלָץ',
                'de_value' => 'Empfohlen',
                'es_value' => 'Recomendado',
                'fr_value' => 'Recommandé',
                'ko_value' => '추천',
                'ja_value' => 'おすすめされた',
                'zh_value' => '推荐的',
                'fil_value' => 'Inirerekomenda',
                'ar_value' => 'موصى به',
            ]
        ];
        /*
      | upsert
      |--------------------------------------------------------------------------
      | We are using upsert here as it functions to either insert or update records efficiently.
      | If a record already exists, it updates it; if not, it inserts a new record.
      | This operation compares records using a unique key and supports handling multiple records in a single operation.
      */
        DB::table('language_constant')->upsert(
            $language_constant_record,
            ['id'], // Unique column to determine if a row exists
            ['constant_name', 'value', 'pt_value', 'vi_value', 'he_value', 'de_value', 'es_value', 'fr_value', 'ko_value', 'ja_value', 'zh_value', 'fil_value', 'ar_value']
        );
    }
}
