<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $service_settings_record = [
            [
                'id' => 1,
                'service_cat_id' => 1,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 25,
                'tax' => 12,
                'admin_commission' => 5,
                'shopper_admin_commission' => Null,
                'cancel_charge' => Null,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 2,
                'service_cat_id' => 2,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 40,
                'tax' => 10,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => Null,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 3,
                'service_cat_id' => 3,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 5,
                'admin_commission' => 5,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 4,
                'service_cat_id' => 4,
                'provider_accept_timeout' => 90,
                'provider_search_radius' => 25,
                'tax' => 10,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 10,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 5,
                'service_cat_id' => 5,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 120,
                'tax' => 10,
                'admin_commission' => 10,
                'shopper_admin_commission' => 20.00,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 6,
                'service_cat_id' => 6,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 25,
                'tax' => 12,
                'admin_commission' => 12,
                'shopper_admin_commission' => 15.00,
                'cancel_charge' => 5,
                'delivery_charge' => 150,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 7,
                'service_cat_id' => 7,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 25,
                'tax' => 12,
                'admin_commission' => 12,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => 2500,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 8,
                'service_cat_id' => 8,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 25,
                'tax' => 12,
                'admin_commission' => 12,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => 100,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 9,
                'service_cat_id' => 9,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 30,
                'tax' => 12,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => 50,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 10,
                'service_cat_id' => 10,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 25,
                'tax' => 10,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 11,
                'service_cat_id' => 11,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 10,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => Null,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 12,
                'service_cat_id' => 12,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 5,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 13,
                'service_cat_id' => 13,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 0,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 14,
                'service_cat_id' => 14,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 15,
                'service_cat_id' => 15,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 16,
                'service_cat_id' => 16,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 10,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => Null,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 17,
                'service_cat_id' => 17,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 18,
                'service_cat_id' => 18,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 19,
                'service_cat_id' => 19,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 20,
                'service_cat_id' => 20,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 21,
                'service_cat_id' => 21,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 22,
                'service_cat_id' => 22,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 23,
                'service_cat_id' => 23,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 24,
                'service_cat_id' => 24,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 25,
                'service_cat_id' => 25,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 26,
                'service_cat_id' => 26,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 27,
                'service_cat_id' => 27,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 0,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 28,
                'service_cat_id' => 28,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 0,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 29,
                'service_cat_id' => 29,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 30,
                'service_cat_id' => 30,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 5,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => 1,
            ],
            [
                'id' => 31,
                'service_cat_id' => 31,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 25,
                'tax' => 10,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => Null,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => Null,
            ],
            [
                'id' => 32,
                'service_cat_id' => 32,
                'provider_accept_timeout' => 60,
                'provider_search_radius' => 25,
                'tax' => 10,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => Null,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => Null,
            ],
            [
                'id' => 33,
                'service_cat_id' => 33,
                'provider_accept_timeout' => Null,
                'provider_search_radius' => Null,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => Null,
            ],
            [
                'id' => 34,
                'service_cat_id' => 52,
                'provider_accept_timeout' => Null,
                'provider_search_radius' => Null,
                'tax' => 0,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => Null,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => Null,
            ],
            [
                'id' => 35,
                'service_cat_id' => 57,
                'provider_accept_timeout' => Null,
                'provider_search_radius' => Null,
                'tax' => 10,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => Null,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => Null,
            ],
            [
                'id' => 36,
                'service_cat_id' => 51,
                'provider_accept_timeout' => Null,
                'provider_search_radius' => Null,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => Null,
            ],
            [
                'id' => 37,
                'service_cat_id' => 53,
                'provider_accept_timeout' => Null,
                'provider_search_radius' => Null,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => Null,
            ],
            [
                'id' => 38,
                'service_cat_id' => 54,
                'provider_accept_timeout' => Null,
                'provider_search_radius' => Null,
                'tax' => 0  ,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => NUll,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => Null,
            ],
            [
                'id' => 39,
                'service_cat_id' => 55,
                'provider_accept_timeout' => Null,
                'provider_search_radius' => Null,
                'tax' => 10,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => Null,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => Null,
            ],
            [
                'id' => 40,
                'service_cat_id' => 56,
                'provider_accept_timeout' => Null,
                'provider_search_radius' => Null,
                'tax' => 0,
                'admin_commission' => 10,
                'shopper_admin_commission' => Null,
                'cancel_charge' => Null,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => Null,
            ],
            [
                'id' => 41,
                'service_cat_id' => 59,
                'provider_accept_timeout' => Null,
                'provider_search_radius' => Null,
                'tax' => 12,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => Null,
            ],
            [
                'id' => 42,
                'service_cat_id' => 65,
                'provider_accept_timeout' => Null,
                'provider_search_radius' => Null,
                'tax' => 0,
                'admin_commission' => 15,
                'shopper_admin_commission' => Null,
                'cancel_charge' => 5,
                'delivery_charge' => Null,
                'surcharge_timings_status' => 0,
                'status' => Null,
            ],


        ];

        /*
    | upsert
    |--------------------------------------------------------------------------
    | We are using upsert here as it functions to either insert or update records efficiently.
    | If a record already exists, it updates it; if not, it inserts a new record.
    | This operation compares records using a unique key and supports handling multiple records in a single operation.
    */
        DB::table('service_settings')->upsert(
            $service_settings_record,
            ['id'], // Unique column to determine if a row exists
            ['service_cat_id','provider_accept_timeout','provider_search_radius','tax','admin_commission','shopper_admin_commission','cancel_charge','delivery_charge','surcharge_timings_status','status']
        );
    }
}
