<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $service_category_record = [
                [
                    'id' => 11,
                    'name' => 'Dog Walking',
                    'slug' => 'dog-walking',
                    'ja_name' => '犬の散歩',
                    'pt_name' => 'Passear com cachorro',
                    'vi_name' => 'Dắt chó đi dạo',
                    'he_name' => 'טיולי כלבים',
                    'de_name' => 'Hundespaziergang',
                    'es_name' => 'pasear perros',
                    'fr_name' => 'Promenade de chien',
                    'ko_name' => '개 산책',
                    'zh_name' => '遛狗',
                    'fil_name' => 'Naglalakad ng Aso',
                    'ar_name' => 'كلب يمشي',
                    'icon_name' => '06353020221606.png',
                    'banner_image' => '9102311202418072.jpg',
                    'display_order' => 2,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 12,
                    'name' => 'Baby Care',
                    'slug' => 'baby-care',
                    'ja_name' => 'ベビーケア',
                    'pt_name' => 'Cuidados com o bebê',
                    'vi_name' => 'Chăm sóc em bé',
                    'he_name' => 'טיפול בתינוק',
                    'de_name' => 'Babypflege',
                    'es_name' => 'Cuidado del bebé',
                    'fr_name' => 'Soins pour bébé',
                    'ko_name' => '아기 케어',
                    'zh_name' => 'ベビーケア',
                    'fil_name' => 'Pangangalaga sa Sanggol',
                    'ar_name' => 'عناية الطفل',
                    'icon_name' => '06354020221606.png',
                    'banner_image' => '3171513202212029.jpg',
                    'display_order' => 5,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 13,
                    'name' => 'Pet Care',
                    'slug' => 'pet-care',
                    'ja_name' => 'ペットケア',
                    'pt_name' => 'Cuidados com animais de estimação',
                    'vi_name' => 'Chăm sóc thú cưng',
                    'he_name' => 'טיפול לחיות מחמד',
                    'de_name' => 'Haustierpflege',
                    'es_name' => 'Cuidado de mascotas',
                    'fr_name' => 'Soins pour animaux de compagnie',
                    'ko_name' => '애완동물 관리',
                    'zh_name' => '宠物护理',
                    'fil_name' => 'Pangangalaga sa Alagang Hayop',
                    'ar_name' => 'رعاية الحيوانات الاليفة',
                    'icon_name' => '06355120221606.png',
                    'banner_image' => '4361513202212021.jpg',
                    'display_order' => 6,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 14,
                    'name' => 'Workout Trainer',
                    'slug' => 'workout-trainer',
                    'ja_name' => 'ワークアウトトレーナー',
                    'pt_name' => 'Treinador de treino',
                    'vi_name' => 'Huấn luyện viên tập luyện',
                    'he_name' => 'מאמן אימון',
                    'de_name' => 'Workout-Trainer',
                    'es_name' => 'Entrenador de entrenamiento',
                    'fr_name' => 'Entraîneur d\'entraînement',
                    'ko_name' => '운동 트레이너',
                    'zh_name' => '健身教练',
                    'fil_name' => 'Tagasanay sa Pagsasanay',
                    'ar_name' => 'مدرب تجريب',
                    'icon_name' => '06360520221606.png',
                    'banner_image' => '4501513202212026.jpg',
                    'display_order' => 7,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 15,
                    'name' => 'Security Service',
                    'slug' => 'security-service',
                    'ja_name' => 'セキュリティサービス',
                    'pt_name' => 'Serviço de Segurança',
                    'vi_name' => 'Dịch vụ an ninh',
                    'he_name' => 'שירות ביטחון',
                    'de_name' => 'Sicherheitsdienst',
                    'es_name' => 'Servicio de seguridad',
                    'fr_name' => 'Service de sécurité',
                    'ko_name' => '보안 서비스',
                    'zh_name' => '安全服务',
                    'fil_name' => 'Serbisyong Pangseguridad',
                    'ar_name' => 'خدمات الأمن',
                    'icon_name' => '06411320221606.png',
                    'banner_image' => '1021613202212028.jpg',
                    'display_order' => 8,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 16,
                    'name' => 'Tutors',
                    'slug' => 'my-tutor',
                    'ja_name' => '講師',
                    'pt_name' => 'Tutoras',
                    'vi_name' => 'Gia sư',
                    'he_name' => 'חונכים',
                    'de_name' => 'Nachhilfelehrerin',
                    'es_name' => 'Tutoras',
                    'fr_name' => 'Tutrices',
                    'ko_name' => '튜터',
                    'zh_name' => '导师',
                    'fil_name' => 'Mga tagapagturo',
                    'ar_name' => 'مدرسون',
                    'icon_name' => '06412420221606.png',
                    'banner_image' => '8201613202212024.jpg',
                    'display_order' => 1,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 17,
                    'name' => 'Beauty Service',
                    'slug' => 'beauty-service',
                    'ja_name' => '美容サービス',
                    'pt_name' => 'Serviço de Beleza',
                    'vi_name' => 'Dịch vụ làm đẹp',
                    'he_name' => 'שירות יופי',
                    'de_name' => 'Schönheitsservice',
                    'es_name' => 'Servicio de belleza',
                    'fr_name' => 'Service de beauté',
                    'ko_name' => '뷰티 서비스',
                    'zh_name' => '美容服务',
                    'fil_name' => 'Serbisyo sa Pagpapaganda',
                    'ar_name' => 'خدمة التجميل',
                    'icon_name' => '06413520221606.png',
                    'banner_image' => '7293312202212027.jpg',
                    'display_order' => 4,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 18,
                    'name' => 'Massage Service',
                    'slug' => 'massage-service',
                    'ja_name' => 'マッサージサービス',
                    'pt_name' => 'Serviço de Massagem',
                    'vi_name' => 'Dịch vụ mát-xa',
                    'he_name' => 'שירות עיסוי',
                    'de_name' => 'Massageservice',
                    'es_name' => 'Servicio de masajes',
                    'fr_name' => 'Service de massage',
                    'ko_name' => '마사지 서비스',
                    'zh_name' => '按摩服务',
                    'fil_name' => 'Serbisyong Masahe',
                    'ar_name' => 'خدمة التدليك',
                    'icon_name' => '06363720221606.png',
                    'banner_image' => '9131713202212023.jpg',
                    'display_order' => 9,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 19,
                    'name' => 'Home Cleaning',
                    'slug' => 'home-cleaning',
                    'ja_name' => 'ホームクリーニング',
                    'pt_name' => 'Limpeza de casa',
                    'vi_name' => 'Vệ sinh nhà cửa',
                    'he_name' => 'ניקיון הבית',
                    'de_name' => 'Hausreinigung',
                    'es_name' => 'Limpieza del hogar',
                    'fr_name' => 'Nettoyage de la maison',
                    'ko_name' => '집 청소',
                    'zh_name' => '家庭清洁',
                    'fil_name' => 'Paglilinis ng Bahay',
                    'ar_name' => 'تنظيف المنزل',
                    'icon_name' => '06364920221606.png',
                    'banner_image' => '5261713202212021.jpg',
                    'display_order' => 3,
                    'category_type' => 3,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 20,
                    'name' => 'Gardening',
                    'slug' => 'my-garden',
                    'ja_name' => '園芸',
                    'pt_name' => 'Jardinagem',
                    'vi_name' => 'Làm vườn',
                    'he_name' => 'גַנָנוּת',
                    'de_name' => 'Gartenarbeit',
                    'es_name' => 'Jardinería',
                    'fr_name' => 'Jardinage',
                    'ko_name' => '원예',
                    'zh_name' => '园艺',
                    'fil_name' => 'Paghahalaman',
                    'ar_name' => 'الحدائق',
                    'icon_name' => '06370420221606.png',
                    'banner_image' => '9401713202212022.jpg',
                    'display_order' => 11,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 22,
                    'name' => 'Snow Blowers',
                    'slug' => 'snow-blowers',
                    'ja_name' => '除雪機',
                    'pt_name' => 'Sopradores de neve',
                    'vi_name' => 'Máy thổi tuyết',
                    'he_name' => 'מפוחי שלג',
                    'de_name' => 'Schneefräsen',
                    'es_name' => 'Sopladores de nieve',
                    'fr_name' => 'Souffleuses à neige',
                    'ko_name' => '제설기',
                    'zh_name' => '吹雪机',
                    'fil_name' => 'Mga Snow Blower',
                    'ar_name' => 'نافخات الثلج',
                    'icon_name' => '06371520221606.png',
                    'banner_image' => '8581713202212021.jpg',
                    'display_order' => 12,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 23,
                    'name' => 'Laundry Service',
                    'slug' => 'laundry-service',
                    'ja_name' => 'ランドリーサービス',
                    'pt_name' => 'Serviço de Lavanderia',
                    'vi_name' => 'Dịch vụ giặt là',
                    'he_name' => 'שירות כביסה',
                    'de_name' => 'Wäscheservice',
                    'es_name' => 'Servicio de lavandería',
                    'fr_name' => 'Blanchisserie',
                    'ko_name' => '세탁 서비스',
                    'zh_name' => '洗衣服务',
                    'fil_name' => 'Serbisyo sa Paglalaba',
                    'ar_name' => 'خدمة غسيل الملابس',
                    'icon_name' => '06372920221606.png',
                    'banner_image' => '7101813202212025.jpg',
                    'display_order' => 13,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 24,
                    'name' => 'Maid Service',
                    'slug' => 'maid-service',
                    'ja_name' => 'メイドサービス',
                    'pt_name' => 'Serviço de limpeza',
                    'vi_name' => 'Dịch vụ giúp việc',
                    'he_name' => 'שירות חדרנית',
                    'de_name' => 'Haushaltshilfe',
                    'es_name' => 'Servicio de mucama',
                    'fr_name' => 'Service de ménage',
                    'ko_name' => '하녀 서비스',
                    'zh_name' => '女佣服务',
                    'fil_name' => 'Serbisyong Kasambahay',
                    'ar_name' => 'خدمة الخادمة',
                    'icon_name' => '06374220221606.png',
                    'banner_image' => '7271913202212023.jpg',
                    'display_order' => 14,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 25,
                    'name' => 'Pest Control',
                    'slug' => 'pest-control',
                    'ja_name' => '害虫駆除',
                    'pt_name' => 'Controle de pragas',
                    'vi_name' => 'Kiểm soát dịch hại',
                    'he_name' => 'הדברה',
                    'de_name' => 'Schädlingsbekämpfung',
                    'es_name' => 'Control de plagas',
                    'fr_name' => 'Lutte antiparasitaire',
                    'ko_name' => '해충 관리',
                    'zh_name' => '害虫防治',
                    'fil_name' => 'Pagkontrol ng Peste',
                    'ar_name' => 'مكافحة الآفات',
                    'icon_name' => '06375820221606.png',
                    'banner_image' => '9471913202212024.jpg',
                    'display_order' => 15,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 26,
                    'name' => 'AC Repair',
                    'slug' => 'ac-repair',
                    'ja_name' => 'エアコン修理',
                    'pt_name' => 'Reparo de AC',
                    'vi_name' => 'Sửa chữa AC',
                    'he_name' => 'תיקון AC',
                    'de_name' => 'Klimaanlagenreparatur',
                    'es_name' => 'Reparación de aire acondicionado',
                    'fr_name' => 'Réparation de climatisation',
                    'ko_name' => '에어컨 수리',
                    'zh_name' => '空调维修',
                    'fil_name' => 'Pag-aayos ng AC',
                    'ar_name' => 'تصليح مكيفات الهواء',
                    'icon_name' => '06380820221606.png',
                    'banner_image' => '2481813202212024.jpg',
                    'display_order' => 16,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 27,
                    'name' => 'Electricians',
                    'slug' => 'electricians',
                    'ja_name' => '電気技師',
                    'pt_name' => 'Eletricistas',
                    'vi_name' => 'Thợ điện',
                    'he_name' => 'חשמלאים',
                    'de_name' => 'Elektrikerinnen',
                    'es_name' => 'Electricistas',
                    'fr_name' => 'Électriciennes',
                    'ko_name' => '전기 기술자',
                    'zh_name' => '电工',
                    'fil_name' => 'Mga electrician',
                    'ar_name' => 'اختصاصي بالكهرباء',
                    'icon_name' => '06414520221606.png',
                    'banner_image' => '6202013202212022.jpg',
                    'display_order' => 19,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 28,
                    'name' => 'Car Wash',
                    'slug' => 'car-wash',
                    'ja_name' => '洗車',
                    'pt_name' => 'Lavagem de carros',
                    'vi_name' => 'Rửa xe',
                    'he_name' => 'שטיפת מכוניות',
                    'de_name' => 'Waschanlage',
                    'es_name' => 'Lavado de autos',
                    'fr_name' => 'Lavage de voiture',
                    'ko_name' => '세차장',
                    'zh_name' => '洗车',
                    'fil_name' => 'Paghuhugas ng Sasakyan',
                    'ar_name' => 'غسيل سيارة',
                    'icon_name' => '06415420221606.png',
                    'banner_image' => '9292013202212025.jpg',
                    'display_order' => 18,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 29,
                    'name' => 'Car repair',
                    'slug' => 'car-repair',
                    'ja_name' => '車の修理',
                    'pt_name' => 'Reparo de carro',
                    'vi_name' => 'Sửa chữa ô tô',
                    'he_name' => 'תיקון רכב',
                    'de_name' => 'Autoreparatur',
                    'es_name' => 'Reparación de automóviles',
                    'fr_name' => 'Réparation de voiture',
                    'ko_name' => '자동차 수리',
                    'zh_name' => '汽车维修',
                    'fil_name' => 'Pag-aayos ng sasakyan',
                    'ar_name' => 'إصلاح السيارات',
                    'icon_name' => '06420520221606.png',
                    'banner_image' => '5392013202212028.jpg',
                    'display_order' => 20,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 30,
                    'name' => 'Tow Truck',
                    'slug' => 'tow-truck',
                    'ja_name' => 'レッカー車',
                    'pt_name' => 'Caminhão de reboque',
                    'vi_name' => 'Xe kéo',
                    'he_name' => 'משאית גרר',
                    'de_name' => 'Abschleppwagen',
                    'es_name' => 'Carro de remolque',
                    'fr_name' => 'Dépanneuse',
                    'ko_name' => '견인차',
                    'zh_name' => '拖车',
                    'fil_name' => 'Tow Truck',
                    'ar_name' => 'سحب الشاحنة',
                    'icon_name' => '06385820221606.png',
                    'banner_image' => '4512013202212021.jpg',
                    'display_order' => 17,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 33,
                    'name' => 'Plumbers',
                    'slug' => 'plumbers',
                    'ja_name' => '配管工',
                    'pt_name' => 'Encanadoras',
                    'vi_name' => 'Thợ sửa ống nước',
                    'he_name' => 'אינסטלטורים',
                    'de_name' => 'Klempnerinnen',
                    'es_name' => 'Fontaneras',
                    'fr_name' => 'Mga tubero',
                    'ko_name' => '배관공',
                    'zh_name' => '水管工',
                    'fil_name' => 'Mga tubero',
                    'ar_name' => 'سباكين',
                    'icon_name' => '06391220221606.png',
                    'banner_image' => '6122113202212027.jpg',
                    'display_order' => 10,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 36,
                    'name' => 'DJ Guide',
                    'slug' => 'dj-guide',
                    'ja_name' => 'DJガイド',
                    'pt_name' => 'Guia de DJ',
                    'vi_name' => 'Hướng dẫn DJ',
                    'he_name' => 'מדריך DJ',
                    'de_name' => 'DJ-Leitfaden',
                    'es_name' => 'Guía de DJ',
                    'fr_name' => 'Guide du DJ',
                    'ko_name' => 'DJ 가이드',
                    'zh_name' => 'DJ 指南',
                    'fil_name' => 'Gabay ni DJ',
                    'ar_name' => 'دليل DJ',
                    'icon_name' => '05323420232704.png',
                    'banner_image' => '8414009202307046.jpg',
                    'display_order' => 21,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 37,
                    'name' => 'Carpenter',
                    'slug' => 'carpenter',
                    'ja_name' => '大工',
                    'pt_name' => 'Carpinteira',
                    'vi_name' => 'Thợ mộc',
                    'he_name' => 'נַגָר',
                    'de_name' => 'Tischler',
                    'es_name' => 'Carpintera',
                    'fr_name' => 'Menuisier',
                    'ko_name' => '목수',
                    'zh_name' => '木匠',
                    'fil_name' => 'karpintero',
                    'ar_name' => 'النجار',
                    'icon_name' => '05311820232704.png',
                    'banner_image' => '5032805202327048.png',
                    'display_order' => 22,
                    'category_type' => 3,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 38,
                    'name' => 'Tour Guide',
                    'slug' => 'tour-guide',
                    'ja_name' => 'ツアーガイド',
                    'pt_name' => 'Guia de turismo',
                    'vi_name' => 'Hướng dẫn viên du lịch',
                    'he_name' => 'מדריך טיולים',
                    'de_name' => 'Reiseführer',
                    'es_name' => 'Guía Turístico',
                    'fr_name' => 'Guide touristique',
                    'ko_name' => '투어 가이드',
                    'zh_name' => '导游',
                    'fil_name' => 'Tour Guide',
                    'ar_name' => 'مرشد سياحي',
                    'icon_name' => '05335820232704.png',
                    'banner_image' => '9583305202327042.png',
                    'display_order' => 23,
                    'category_type' => 3,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 39,
                    'name' => 'Carpet Cleaner',
                    'slug' => 'carpet-cleaner',
                    'ja_name' => 'カーペットクリーナー',
                    'pt_name' => 'Limpador de carpetes',
                    'vi_name' => 'Máy giặt thảm',
                    'he_name' => 'מנקה שטיחים',
                    'de_name' => 'Teppichreiniger',
                    'es_name' => 'Limpiadora de alfombras',
                    'fr_name' => 'Nettoyeur de tapis',
                    'ko_name' => '카펫 청소기',
                    'zh_name' => '地毯清洁剂',
                    'fil_name' => 'Tagalinis ng Carpet',
                    'ar_name' => 'منظف السجاد',
                    'icon_name' => '05371720232704.png',
                    'banner_image' => '1173705202327046.png',
                    'display_order' => 24,
                    'category_type' => 3,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 40,
                    'name' => 'Sofa Repair',
                    'slug' => 'sofa-repair',
                    'ja_name' => 'ソファー修理',
                    'pt_name' => 'Reparo de Sofá',
                    'vi_name' => 'Sửa ghế sofa',
                    'he_name' => 'תיקון ספות',
                    'de_name' => 'Sofa-Reparatur',
                    'es_name' => 'Reparación de sofás',
                    'fr_name' => 'Réparation de canapé',
                    'ko_name' => '소파 수리',
                    'zh_name' => '沙发维修',
                    'fil_name' => 'Pag-aayos ng Sofa',
                    'ar_name' => 'إصلاح الأريكة',
                    'icon_name' => '05383120232704.png',
                    'banner_image' => '9313805202327046.png',
                    'display_order' => 25,
                    'category_type' => 3,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 41,
                    'name' => 'Catering',
                    'slug' => 'catering',
                    'ja_name' => 'ケータリング',
                    'pt_name' => 'Restauração',
                    'vi_name' => 'Dịch vụ ăn uống',
                    'he_name' => 'הַסעָדָה',
                    'de_name' => 'Gastronomie',
                    'es_name' => 'Abastecimiento',
                    'fr_name' => 'Restauration',
                    'ko_name' => '케이터링',
                    'zh_name' => '餐饮',
                    'fil_name' => 'Catering',
                    'ar_name' => 'تقديم الطعام',
                    'icon_name' => '05392920232704.png',
                    'banner_image' => '8293905202327045.png',
                    'display_order' => 26,
                    'category_type' => 3,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 42,
                    'name' => 'Real Estate Agent',
                    'slug' => 'real-estate-agent',
                    'ja_name' => '不動産業者',
                    'pt_name' => 'Agente imobiliário',
                    'vi_name' => 'Môi giới bất động sản',
                    'he_name' => 'סוכן נדל"ן',
                    'de_name' => 'Immobilienmakler',
                    'es_name' => 'Agente inmobiliario',
                    'fr_name' => 'Agent immobilier',
                    'ko_name' => '부동산 중개인',
                    'zh_name' => '房地产经纪人',
                    'fil_name' => 'Ahente ng Real Estate',
                    'ar_name' => 'سمسار',
                    'icon_name' => '05404820232704.png',
                    'banner_image' => '8484005202327045.png',
                    'display_order' => 27,
                    'category_type' => 3,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 43,
                    'name' => 'Computer Repair',
                    'slug' => 'computer-repair',
                    'ja_name' => 'コンピュータ修理',
                    'pt_name' => 'Reparo de Computador',
                    'vi_name' => 'Sửa chữa máy tính',
                    'he_name' => 'תיקון מחשב',
                    'de_name' => 'Computerreparatur',
                    'es_name' => 'Reparación de computadoras',
                    'fr_name' => 'Réparation d\'ordinateur',
                    'ko_name' => '컴퓨터 수리',
                    'zh_name' => '电脑维修',
                    'fil_name' => 'Pag-aayos ng Computer',
                    'ar_name' => 'إصلاح الكمبيوتر',
                    'icon_name' => '05415120232704.png',
                    'banner_image' => '8514105202327043.png',
                    'display_order' => 28,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 44,
                    'name' => 'Physiotherapy',
                    'slug' => 'physiotherapy',
                    'ja_name' => '理学療法',
                    'pt_name' => 'Fisioterapia',
                    'vi_name' => 'Vật lý trị liệu',
                    'he_name' => 'פִיסִיוֹתֶרָפִּיָה',
                    'de_name' => 'Physiotherapie',
                    'es_name' => 'Fisioterapia',
                    'fr_name' => 'Physiothérapie',
                    'ko_name' => '물리치료',
                    'zh_name' => '理疗',
                    'fil_name' => 'Physiotherapy',
                    'ar_name' => 'العلاج الطبيعي',
                    'icon_name' => '05435420232704.png',
                    'banner_image' => '5544305202327042.png',
                    'display_order' => 29,
                    'category_type' => 3,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 45,
                    'name' => 'Photography',
                    'slug' => 'photography',
                    'ja_name' => '写真',
                    'pt_name' => 'Fotografia',
                    'vi_name' => 'Nhiếp ảnh',
                    'he_name' => 'צילום',
                    'de_name' => 'Fotografie',
                    'es_name' => 'Fotografía',
                    'fr_name' => 'Photographie',
                    'ko_name' => '사진술',
                    'zh_name' => '摄影',
                    'fil_name' => 'Photography',
                    'ar_name' => 'التصوير',
                    'icon_name' => '05444520232704.png',
                    'banner_image' => '6454405202327043.png',
                    'display_order' => 30,
                    'category_type' => 3,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 46,
                    'name' => 'Fire Fighter',
                    'slug' => 'fire-fighter',
                    'ja_name' => '消防士',
                    'pt_name' => 'Bombeira',
                    'vi_name' => 'Lính cứu hỏa',
                    'he_name' => 'לוחם אש',
                    'de_name' => 'Feuerwehrfrau',
                    'es_name' => 'Bombera',
                    'fr_name' => 'Pompier',
                    'ko_name' => '소방수',
                    'zh_name' => '消防员',
                    'fil_name' => 'Bumbero',
                    'ar_name' => 'رجال الاطفاء',
                    'icon_name' => '05453520232704.png',
                    'banner_image' => '4354505202327045.png',
                    'display_order' => 31,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 47,
                    'name' => 'Mobile Technician',
                    'slug' => 'mobile-technician',
                    'ja_name' => 'モバイル技術者',
                    'pt_name' => 'Técnico Móvel',
                    'vi_name' => 'Kỹ thuật viên di động',
                    'he_name' => 'טכנאי נייד',
                    'de_name' => 'Mobiler Techniker',
                    'es_name' => 'Técnica móvil',
                    'fr_name' => 'Technicien mobile',
                    'ko_name' => '모바일 기술자',
                    'zh_name' => '移动技术员',
                    'fil_name' => 'Mobile Technician',
                    'ar_name' => 'فني موبايل',
                    'icon_name' => '05465120232704.png',
                    'banner_image' => '8514605202327042.png',
                    'display_order' => 32,
                    'category_type' => 3,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 48,
                    'name' => 'Mechanic',
                    'slug' => 'mechanic',
                    'ja_name' => 'メカニック',
                    'pt_name' => 'Mecânica',
                    'vi_name' => 'Thợ cơ khí',
                    'he_name' => 'מְכוֹנַאִי',
                    'de_name' => 'Mechanikerin',
                    'es_name' => 'Mecánica',
                    'fr_name' => 'Mécanicienne',
                    'ko_name' => '정비공',
                    'zh_name' => '机械',
                    'fil_name' => 'Mekaniko',
                    'ar_name' => 'ميكانيكي',
                    'icon_name' => '05473820232704.png',
                    'banner_image' => '1384705202327048.png',
                    'display_order' => 42,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 49,
                    'name' => 'Home Painting',
                    'slug' => 'home-painting',
                    'ja_name' => 'ホームペインティング',
                    'pt_name' => 'Pintura de casa',
                    'vi_name' => 'Sơn nhà',
                    'he_name' => 'ציור ביתי',
                    'de_name' => 'Malerarbeiten zu Hause',
                    'es_name' => 'Pintura para el hogar',
                    'fr_name' => 'Peinture de maison',
                    'ko_name' => '홈 페인팅',
                    'zh_name' => '家庭绘画',
                    'fil_name' => 'Pagpipinta ng Bahay',
                    'ar_name' => 'دهان المنزل',
                    'icon_name' => '05483020232704.png',
                    'banner_image' => '2304805202327041.png',
                    'display_order' => 33,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 50,
                    'name' => 'Locksmith',
                    'slug' => 'locksmith',
                    'ja_name' => '鍵屋',
                    'pt_name' => 'Serralheiro',
                    'vi_name' => 'thợ khóa',
                    'he_name' => 'מַסגֵר',
                    'de_name' => 'Schlosser',
                    'es_name' => 'Cerrajero',
                    'fr_name' => 'Serrurier',
                    'ko_name' => '자물쇠공',
                    'zh_name' => '锁匠',
                    'fil_name' => 'Locksmith',
                    'ar_name' => 'قفال',
                    'icon_name' => '05490920232704.png',
                    'banner_image' => '9094905202327042.png',
                    'display_order' => 34,
                    'category_type' => 3,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 51,
                    'name' => 'Insurance Agent',
                    'slug' => 'insurance-agent',
                    'ja_name' => '保険代理店',
                    'pt_name' => 'Agente de seguros',
                    'vi_name' => 'Đại lý bảo hiểm',
                    'he_name' => 'סוכן ביטוח',
                    'de_name' => 'Versicherungsvertreter',
                    'es_name' => 'Agente de seguros',
                    'fr_name' => 'Agent d\'assurance',
                    'ko_name' => '보험 중개인',
                    'zh_name' => '保险代理人',
                    'fil_name' => 'Ahente ng Seguro',
                    'ar_name' => 'عامل تأمين',
                    'icon_name' => '05500820232704.png',
                    'banner_image' => '7085005202327046.png',
                    'display_order' => 35,
                    'category_type' => 3,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 52,
                    'name' => 'Lawyer Service',
                    'slug' => 'lawyer-service',
                    'ja_name' => '弁護士サービス',
                    'pt_name' => 'Serviço de advogado',
                    'vi_name' => 'Dịch vụ luật sư',
                    'he_name' => 'שירות עורכי דין',
                    'de_name' => 'Anwaltsservice',
                    'es_name' => 'Servicio de Abogados',
                    'fr_name' => 'Service d\'avocat',
                    'ko_name' => '변호사 서비스',
                    'zh_name' => '律师服务',
                    'fil_name' => 'Serbisyong Abugado',
                    'ar_name' => 'خدمة المحامي',
                    'icon_name' => '05504720232704.png',
                    'banner_image' => '6475005202327049.png',
                    'display_order' => 36,
                    'category_type' => 3,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 53,
                    'name' => 'Interior Design',
                    'slug' => 'interior-design',
                    'ja_name' => 'インテリアデザイン',
                    'pt_name' => 'Design de Interiores',
                    'vi_name' => 'Thiết kế nội thất',
                    'he_name' => 'Thiết kế nội thất',
                    'de_name' => 'Innenarchitektur',
                    'es_name' => 'Diseño de interiores',
                    'fr_name' => 'Design d\'intérieur',
                    'ko_name' => '인테리어 디자인',
                    'zh_name' => '室内设计',
                    'fil_name' => 'Disenyong Panloob',
                    'ar_name' => 'تصميم داخلي',
                    'icon_name' => '05513720232704.png',
                    'banner_image' => '9375105202327048.png',
                    'display_order' => 37,
                    'category_type' => 3,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 54,
                    'name' => 'Language Translator',
                    'slug' => 'language-translator',
                    'ja_name' => '言語翻訳者',
                    'pt_name' => 'Tradutor de idiomas',
                    'vi_name' => 'Trình dịch ngôn ngữ',
                    'he_name' => 'מתרגם שפה',
                    'de_name' => 'Sprachübersetzer',
                    'es_name' => 'Traductor de idiomas',
                    'fr_name' => 'Traducteur de langue',
                    'ko_name' => '언어 번역기',
                    'zh_name' => '语言翻译',
                    'fil_name' => 'Tagasalin ng Wika',
                    'ar_name' => 'مترجم لغة',
                    'icon_name' => '05544520232704.png',
                    'banner_image' => '6455405202327044.png',
                    'display_order' => 38,
                    'category_type' => 3,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
                [
                    'id' => 55,
                    'name' => 'TV Repair',
                    'slug' => 'tv-repair',
                    'ja_name' => 'テレビの修理',
                    'pt_name' => 'Conserto de TV',
                    'vi_name' => 'Sửa tivi',
                    'he_name' => 'תיקון טלוויזיה',
                    'de_name' => 'TV-Reparatur',
                    'es_name' => 'Reparación de televisores',
                    'fr_name' => 'Réparation de téléviseur',
                    'ko_name' => 'TV수리',
                    'zh_name' => '电视维修',
                    'fil_name' => 'Pag-aayos ng TV',
                    'ar_name' => 'إصلاح التلفاز',
                    'icon_name' => '05560720232704.png',
                    'banner_image' => '3075605202327047.png',
                    'display_order' => 41,
                    'category_type' => 4,
                    'is_sub_cat_flow' => 0,
                    'status' => 1
                ],
        ];
        /*
     | upsert
     |--------------------------------------------------------------------------
     | We are using upsert here as it functions to either insert or update records efficiently.
     | If a record already exists, it updates it; if not, it inserts a new record.
     | This operation compares records using a unique key and supports handling multiple records in a single operation.
     */
        DB::table('service_category')->upsert(
            $service_category_record,
            ['id'], // Unique column to determine if a row exists
            ['name', 'slug', 'ja_name', 'pt_name', 'vi_name', 'he_name', 'de_name', 'es_name', 'fr_name', 'ko_name', 'zh_name', 'fil_name', 'ar_name', 'icon_name', 'banner_image', 'display_order', 'category_type', 'is_sub_cat_flow', 'status']
        );
    }
}
