<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceSliderBannerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $service_slider_banner_record = [
            [
                'id' => 1,
                'service_cat_id' => 17,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 22,
                'banner_image' => '7133311202212023.png',
                'status' => 1,
            ],
            [
                'id' => 2,
                'service_cat_id' => 8,
                'type' => 1,
                'store_id' => 3,
                'ondemand_cat_id' => 0,
                'banner_image' => '2344311202212029.jpg',
                'status' => 1,
            ],
            [
                'id' => 3,
                'service_cat_id' => 8,
                'type' => 1,
                'store_id' => 4,
                'ondemand_cat_id' => 0,
                'banner_image' => '1444311202212026.jpg',
                'status' => 1,
            ],
            [
                'id' => 4,
                'service_cat_id' => 10,
                'type' => 1,
                'store_id' => 1,
                'ondemand_cat_id' => 0,
                'banner_image' => '1250212202212023.jpg',
                'status' => 1,
            ],
            [
                'id' => 5,
                'service_cat_id' => 10,
                'type' => 1,
                'store_id' => 6,
                'ondemand_cat_id' => 0,
                'banner_image' => '5390212202212027.jpg',
                'status' => 1,
            ],
            [
                'id' => 6,
                'service_cat_id' => 5,
                'type' => 1,
                'store_id' => 7,
                'ondemand_cat_id' => 0,
                'banner_image' => '8201812202212022.jpg',
                'status' => 1,
            ],
            [
                'id' => 7,
                'service_cat_id' => 5,
                'type' => 1,
                'store_id' => 8,
                'ondemand_cat_id' => 0,
                'banner_image' => '9271812202212027.jpg',
                'status' => 1,
            ],
            [
                'id' => 8,
                'service_cat_id' => 13,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 6,
                'banner_image' => '8582005202214028.jpg',
                'status' => 1,
            ],
            [
                'id' => 9,
                'service_cat_id' => 11,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 66,
                'banner_image' => '1182605202214028.jpg',
                'status' => 1,
            ],
            [
                'id' => 10,
                'service_cat_id' => 14,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 12,
                'banner_image' => '2060806202214027.jpg',
                'status' => 1,
            ],
            [
                'id' => 11,
                'service_cat_id' => 15,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 14,
                'banner_image' => '9591406202214028.jpg',
                'status' => 1,
            ],
            [
                'id' => 12,
                'service_cat_id' => 16,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 18,
                'banner_image' => '7522406202214021.jpg',
                'status' => 1,
            ],
            [
                'id' => 13,
                'service_cat_id' => 18,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 26,
                'banner_image' => '6153606202214026.jpg',
                'status' => 1,
            ],
            [
                'id' => 14,
                'service_cat_id' => 19,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 32,
                'banner_image' => '3053806202214023.jpg',
                'status' => 1,
            ],
            [
                'id' => 15,
                'service_cat_id' => 20,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 34,
                'banner_image' => '7414406202214021.jpg',
                'status' => 1,
            ],
            [
                'id' => 16,
                'service_cat_id' => 22,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 38,
                'banner_image' => '3264606202214027.jpg',
                'status' => 1,
            ],
            [
                'id' => 17,
                'service_cat_id' => 23,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 43,
                'banner_image' => '7105306202214029.jpg',
                'status' => 1,
            ],
            [
                'id' => 18,
                'service_cat_id' => 24,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 44,
                'banner_image' => '8485806202214023.jpg',
                'status' => 1,
            ],
            [
                'id' => 19,
                'service_cat_id' => 25,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 49,
                'banner_image' => '5170407202214024.jpg',
                'status' => 1,
            ],
            [
                'id' => 20,
                'service_cat_id' => 26,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 52,
                'banner_image' => '4200607202214021.jpg',
                'status' => 1,
            ],
            [
                'id' => 21,
                'service_cat_id' => 27,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 54,
                'banner_image' => '7540707202214023.jpg',
                'status' => 1,
            ],
            [
                'id' => 22,
                'service_cat_id' => 28,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 56,
                'banner_image' => '4571207202214024.jpg',
                'status' => 1,
            ],
            [
                'id' => 23,
                'service_cat_id' => 29,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 60,
                'banner_image' => '7501407202214021.jpg',
                'status' => 1,
            ],
            [
                'id' => 24,
                'service_cat_id' => 30,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 63,
                'banner_image' => '8331807202214024.jpg',
                'status' => 1,
            ],
            [
                'id' => 25,
                'service_cat_id' => 33,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 65,
                'banner_image' => '8152107202214023.jpg',
                'status' => 1,
            ],
            [
                'id' => 26,
                'service_cat_id' => 6,
                'type' => 1,
                'store_id' => 11,
                'ondemand_cat_id' => 0,
                'banner_image' => '8251108202214024.jpg',
                'status' => 1,
            ],
            [
                'id' => 27,
                'service_cat_id' => 6,
                'type' => 1,
                'store_id' => 9,
                'ondemand_cat_id' => 0,
                'banner_image' => '7151208202214021.jpg',
                'status' => 1,
            ],
            [
                'id' => 28,
                'service_cat_id' => 7,
                'type' => 1,
                'store_id' => 18,
                'ondemand_cat_id' => 0,
                'banner_image' => '1463312202214026.jpg',
                'status' => 1,
            ],
            [
                'id' => 29,
                'service_cat_id' => 7,
                'type' => 1,
                'store_id' => 20,
                'ondemand_cat_id' => 0,
                'banner_image' => '8083412202214026.jpg',
                'status' => 1,
            ],
            [
                'id' => 30,
                'service_cat_id' => 9,
                'type' => 1,
                'store_id' => 21,
                'ondemand_cat_id' => 0,
                'banner_image' => '8483810202215028.jpg',
                'status' => 1,
            ],
            [
                'id' => 31,
                'service_cat_id' => 9,
                'type' => 1,
                'store_id' => 22,
                'ondemand_cat_id' => 0,
                'banner_image' => '9143910202215022.jpg',
                'status' => 1,
            ],
            [
                'id' => 32,
                'service_cat_id' => 36,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 68,
                'banner_image' => '4161505202327046.png',
                'status' => 1,
            ],
            [
                'id' => 33,
                'service_cat_id' => 37,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 74,
                'banner_image' => '9155805202327042.png',
                'status' => 1,
            ],
            [
                'id' => 34,
                'service_cat_id' => 38,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 80,
                'banner_image' => '5065905202327046.png',
                'status' => 1,
            ],
            [
                'id' => 35,
                'service_cat_id' => 39,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 85,
                'banner_image' => '3355905202327042.png',
                'status' => 1,
            ],
            [
                'id' => 36,
                'service_cat_id' => 40,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 86,
                'banner_image' => '2140006202327044.png',
                'status' => 1,
            ],
            [
                'id' => 37,
                'service_cat_id' => 41,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 99,
                'banner_image' => '2450006202327042.png',
                'status' => 1,
            ],
            [
                'id' => 38,
                'service_cat_id' => 42,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 95,
                'banner_image' => '9100106202327048.png',
                'status' => 1,
            ],
            [
                'id' => 39,
                'service_cat_id' => 43,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 100,
                'banner_image' => '9380106202327048.png',
                'status' => 1,
            ],
            [
                'id' => 40,
                'service_cat_id' => 44,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 104,
                'banner_image' => '9050206202327043.png',
                'status' => 1,
            ],
            [
                'id' => 41,
                'service_cat_id' => 45,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 110,
                'banner_image' => '8361306202327045.png',
                'status' => 1,
            ],
            [
                'id' => 42,
                'service_cat_id' => 46,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 114,
                'banner_image' => '1031406202327049.png',
                'status' => 1,
            ],
            [
                'id' => 43,
                'service_cat_id' => 47,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 117,
                'banner_image' => '3411406202327045.png',
                'status' => 1,
            ],
            [
                'id' => 44,
                'service_cat_id' => 48,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 121,
                'banner_image' => '1161506202327045.png',
                'status' => 1,
            ],
            [
                'id' => 45,
                'service_cat_id' => 49,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 126,
                'banner_image' => '7351606202327043.png',
                'status' => 1,
            ],
            [
                'id' => 46,
                'service_cat_id' => 50,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 130,
                'banner_image' => '3071706202327042.png',
                'status' => 1,
            ],
            [
                'id' => 47,
                'service_cat_id' => 51,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 133,
                'banner_image' => '7381706202327044.png',
                'status' => 1,
            ],
            [
                'id' => 48,
                'service_cat_id' => 52,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 137,
                'banner_image' => '5472106202327044.png',
                'status' => 1,
            ],
            [
                'id' => 49,
                'service_cat_id' => 53,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 143,
                'banner_image' => '6322206202327046.png',
                'status' => 1,
            ],
            [
                'id' => 50,
                'service_cat_id' => 54,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 146,
                'banner_image' => '7342306202327042.png',
                'status' => 1,
            ],
            [
                'id' => 51,
                'service_cat_id' => 55,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 159,
                'banner_image' => '5072506202327047.png',
                'status' => 1,
            ],
            [
                'id' => 52,
                'service_cat_id' => 12,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 4,
                'banner_image' => '8472910202327042.png',
                'status' => 1,
            ],
            [
                'id' => 53,
                'service_cat_id' => 57,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 171,
                'banner_image' => '5163305202323128.jpeg',
                'status' => 1,
            ],
            [
                'id' => 54,
                'service_cat_id' => 57,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 172,
                'banner_image' => '5504506202323121.jpg',
                'status' => 1,
            ],
            [
                'id' => 55,
                'service_cat_id' => 11,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 174,
                'banner_image' => '4182110202410048.jpg',
                'status' => 1,
            ],
            [
                'id' => 56,
                'service_cat_id' => 16,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 20,
                'banner_image' => '9275211202427047.jpg',
                'status' => 1,
            ],
            [
                'id' => 57,
                'service_cat_id' => 11,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 176,
                'banner_image' => '3020612202409052.png',
                'status' => 1,
            ],
            [
                'id' => 58,
                'service_cat_id' => 11,
                'type' => 2,
                'store_id' => 0,
                'ondemand_cat_id' => 179,
                'banner_image' => '6271806202409075.jfif',
                'status' => 1,
            ],
        ];
        /*
    | upsert
    |--------------------------------------------------------------------------
    | We are using upsert here as it functions to either insert or update records efficiently.
    | If a record already exists, it updates it; if not, it inserts a new record.
    | This operation compares records using a unique key and supports handling multiple records in a single operation.
    */
        DB::table('service_slider_banner')->upsert(
            $service_slider_banner_record,
            ['id'], // Unique column to determine if a row exists
            ['service_cat_id','type','store_id','ondemand_cat_id','banner_image','status']
        );
    }
}
